### ISSUE TITLE
Cloning https://github.com/SwiftJava/javax_swing.git

### ISSUE THREAD

**Issue by rbpaservices** [SwiftJava/SwiftJava#3]
If I am doing something wrong or missed a step in your read me instructions, please point me in the right direction.  the error is error: No version tag found in SwiftJava/examples/Packages/javax_swing.git) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

**Comment by johnno1962** [comment]
Sorry about that. I had to re-create the repo. I’ve created a tag now.

**Comment by rbpaservices** [comment]
Thanks, I will try it again.

**Comment by rbpaservices** [comment]
It seems to have completed fine. There are a number of warnings like 

> main.swift:19:8: note: explicitly cast to Any with 'as Any' to silence this warning
print( ClassNotFoundException(casting: e) )
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          as Any

> main.swift:20:8: note: provide a default value to avoid this warning
print( Throwable(casting: e) )
       ^~~~~~~~~~~~~~~~~~~~~
                             ?? <#default value#>
As I am just learning how to use swift, I am not sure if these need to be addressed by me in some way.  

If you have any further instructions on how to use this Swift/Java project, run the examples  and include it with my projects, please let me know where I can find it.  Thanks

**Comment by johnno1962** [comment]
What are you trying to develop? For Linux see the example subproject. For Android see the swift-android-samples sub project.

**Comment by rbpaservices** [comment]
I am particularly interested in using the JDBC driver to connect with a DB2
database. I will take a shot at it, but I am not sure I understand how to
develop something like this just from the example.  Thanks for the quick
response.

**Comment by johnno1962** [comment]
There is a JDBC target in the SwiftJava project which should have what you need
