### ISSUE TITLE
The build failed when running the command

### ISSUE THREAD

**Issue by gagaJay** [SwiftJava/SwiftJava#4]
hey guys, I was following the steps mentioned in the README page to run the sample. The command line, however, failed with the below errors: 

swift build -Xlinker -L$JVM_LIBRARY_PATH -Xlinker -rpath -Xlinker $JVM_LIBRARY_PATH -Xlinker -ljvm
error: unknown command: -ljvm
enter `/Applications/Xcode_8.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build --help' for usage information 

Not sure where went long, any idea? thanks in advance.

**Comment by johnno1962** [comment]
Johns-MacBook-Air:swift johnholdsworth$ find $JAVA_HOME -name libjvm.*
/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/server/libjvm.dylib
Johns-MacBook-Air:swift johnholdsworth$

export JVM_LIBRARY_PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/server

**Comment by gagaJay** [comment]
@johnno1962 thanks for you reply. i tried your command but did not work. can you explain a bit what is this doing? 

what is johnholdsworth$ suppose to be? I guess it should be replaced by something else, isn't it? Look forward to hear from you again.

**Comment by spearway** [comment]
On Macos The best way to find Java home is:
export JAVA_HOME=`/usr/libexec/java_home --version 1.8`

Then you can reference the env variable in your build

**Comment by gagaJay** [comment]
How silly I was. now it works after I set the JAVA_HOME correctly. thanks guys!

**Comment by LOG-TAG** [comment]
@gagaJay  1.8 needed right? it doesn't work on 1.6 as JAVA_HOME?
```
apple$ /usr/libexec/java_home -V

Matching Java Virtual Machines (3):

    11.0.2, x86_64:	"OpenJDK 11.0.2"	/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home

    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

Error for jar:
`apples-Air:SwiftJava-master apple$ ./genswift.sh org.slf4j /Workspace/R_AND_D_SWIFT/codegen/libs/slf4j-api-1.7.21.jar



genswift.java:795: local variable isProtocol is accessed from within inner class; needs to be declared final

    							.compareTo(swiftSignatureFor( newMethod(o2), isProtocol, true, true, null));

    							                                             ^

genswift.java:794: local variable isProtocol is accessed from within inner class; needs to be declared final

    					return statics != 0 ? statics : swiftSignatureFor( newMethod(o1), isProtocol, true, true, null)

    					                                                                  ^

2 errors`
