### ISSUE TITLE
how to run the sample code?

### ISSUE THREAD

**Issue by gagaJay** [SwiftJava/SwiftJava#5]
Hey guys, I know this may sound silly but Im not quite sure how to run the example code. 

I have follow the instructions and successfully ran this command:
swift build -Xlinker -L$JVM_LIBRARY_PATH -Xlinker -rpath -Xlinker $JVM_LIBRARY_PATH -Xlinker -ljvm

Then I was trying to figure out how to run those examples. I saw this build_macos.sh file and guess thats the case (since im using mac) so I ran it and got this error:

__TFFFC10java_swift7JavaJNI7initJVMFT7optionsGSqGSaSS__Vs12StaticStringSi_SbU_FGSpVSC12JavaVMOption_SbU0_FGSpGSqSv__Sb in libdebug.a(JavaJNI.swift.o)
ld: symbol(s) not found for architecture x86_64

Don't know whats going on, maybe im on the wrong direction? 

Another question is that, what IDE do you use to edit the code? I have tried to import to the XCode but it does not work because no project file. Can you point me to the right way? Thanks

**Comment by johnno1962** [comment]
Sorry that script was largely for experimentation and there is a mistake in it. Can you add “-ljvm” to it’s last line.

There is no simple answer for how to edit Swift Package manager projects in Xcode. You have to edit individual files.
